name: iOS Build Check Workflow

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Build scheme 
    runs-on: macos-15

    steps:
      - name: "Install Required Items"
        run: |
          brew install xcbeautify
          brew install swiftlint
          set -o pipefail
      - name: Select xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          xcodebuild -scheme boilerplate-ios-swiftui clean build -sdk iphoneos -configuration Development CODE_SIGNING_ALLOWED=No -skipPackagePluginValidation -skipMacroValidation | xcbeautify       
